// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wsr.Data;

namespace Wsr.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20220509163707_Added PoolTables")]
    partial class AddedPoolTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wsr.Models.PoolTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PoolTables");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a6b9908-a634-4ee4-b709-6a1d11d9c617"),
                            Name = "Stół 1"
                        },
                        new
                        {
                            Id = new Guid("31bccfbe-1b8f-42a8-abf9-9507f3e9e95c"),
                            Name = "Stół 2"
                        });
                });

            modelBuilder.Entity("Wsr.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cookie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Wsr.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a2569be-2e85-4a74-83cc-617488aaef13"),
                            HashedPassword = "eb6074157928e8247f4961d2986755af56be13d471c505f78aad24d69d0776ac",
                            IsAdmin = true,
                            Name = "Zbyszek",
                            Salt = "nJubHNpBjFzAGl0Y"
                        },
                        new
                        {
                            Id = new Guid("0e6f3ffd-d62d-428f-b73a-9784d27af0ba"),
                            HashedPassword = "1a7ca80aa0ea0078155976de82b382a437b1e604267bfb23ffc8ba85743a6d22",
                            IsAdmin = false,
                            Name = "Marcel",
                            Salt = "stX0BAQMrBQ+gOkf"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
