// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wsr.Data;

namespace Wsr.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20220703143217_Deleted pooltables from context")]
    partial class Deletedpooltablesfromcontext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wsr.Models.Cost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Costs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d18c8d-9ace-466d-a50a-a42f097e590f"),
                            CostValue = 99.99m,
                            Name = "Cena normalna"
                        },
                        new
                        {
                            Id = new Guid("e4764d18-8890-497c-93a1-cb14e1ce7ee6"),
                            CostValue = 59.99m,
                            Name = "Cena rabatowa"
                        });
                });

            modelBuilder.Entity("Wsr.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cookie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Wsr.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("df87e0bb-39ad-459b-be12-782ba43baed5"),
                            HashedPassword = "f5a1f65ca7592fb5aecdf8adf4bd1ad6d3e6f2cab6f66ee211803003f6ae4ab5",
                            IsAdmin = true,
                            Name = "Zbyszek",
                            Salt = "DKX6KgajQggZRyRL"
                        },
                        new
                        {
                            Id = new Guid("a0ceee57-9bfd-4104-b26a-c69205fa1909"),
                            HashedPassword = "d93ca31b626f62b95e0d833bdc1888e349a21f50de4eb35ff850f25fdcd7d304",
                            IsAdmin = false,
                            Name = "Marcel",
                            Salt = "vY0zUSj2jc59dsQ+"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
