// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wsr.Data;

namespace Wsr.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20220427170246_AddedSaltColumn")]
    partial class AddedSaltColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wsr.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cef78ceb-d75e-4653-8f77-a2cd14773f8d"),
                            HashedPassword = "a3c8a8a46f8c97f7686998978c001470cd257ea579a61e8d5af9ccc56829c4d6",
                            IsAdmin = true,
                            Name = "Zbyszek",
                            Salt = "13ZK7MWPZRNJP/67"
                        },
                        new
                        {
                            Id = new Guid("536097a0-e2f2-4c0e-9e59-254185da7273"),
                            HashedPassword = "f0aee99ae5d1a00725e7fad85320828ae7be00844eb071c322a839c47a73472b",
                            IsAdmin = false,
                            Name = "Marcel",
                            Salt = "jZnBN2IPrczxdV6E"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
